import LocalizedStrings from 'react-native-localization';

// Import translation objects directly
const en = {
  "common": {
    "search": "Search products...",
    "loading": "Loading...",
    "error": "Error",
    "success": "Success",
    "ok": "OK",
    "cancel": "Cancel",
    "save": "Save",
    "edit": "Edit",
    "delete": "Delete",
    "add": "Add",
    "remove": "Remove",
    "yes": "Yes",
    "no": "No",
    "next": "Next",
    "previous": "Previous",
    "done": "Done",
    "submit": "Submit",
    "continue": "Continue",
    "language": "Select Language",
    "invalidEmail": "Please enter a valid email address.",
    "invalidPhone": "Please enter a valid 10-digit phone number."
  },
  "navigation": {
    "products": "Products",
    "explore": "Explore",
    "cart": "Cart",
    "profile": "Profile"
  },
  "home": {
    "welcome": "Welcome to NVS Rice Mall",
    "searchPlaceholder": "Search products...",
    "all": "All",
    "categories": {
      "sonaMasooriRice": "Sona Masoori Rice",
      "parboiledRice": "Parboiled Rice",
      "sonaMasooriSteamRice": "Sona Masoori Steam Rice",
      "sonaMasooriRawRice": "Sona Masoori Raw Rice",
      "rnrSteamRice": "RNR Steam Rice",
      "rnrRice": "RNR Rice",
      "rawRice": "RAW Rice",
      "giraRawRice": "Gira RAW Rice",
      "giraSteamRice": "Gira Steam Rice",
      "bowledRice": "Bowled Rice",
      "brokenRice": "Broken Rice",
      "brokenSteamRice": "Broken Steam Rice",
      "brokenRawRice": "Broken RAW Rice",
      "basmatiRice": "Basmati Rice",
      "jasmineRice": "Jasmine Rice",
      "italiaDosaRice": "Italia Dosa Rice",
      "hmtSteamRice": "HMT Steam Rice"
    },
    "noProductsFound": "No products found",
    "tryDifferentSearch": "Try a different search or category",
    "addToCart": "Add to Cart",
    "discountOff": "% OFF"
  },
  "login": {
    "welcomeBack": "Welcome back to NVS Rice Mart",
    "email": "Email",
    "password": "Password",
    "login": "Login",
    "forgotPassword": "Forgot Password?",
    "noAccount": "Don't have an account?",
    "register": "Register",
    "fillAllFields": "Please fill in all fields.",
    "featureComingSoon": "Feature coming soon!",
    "phone": "Phone",
    "enterPhone": "Enter phone number",
    "sendOTP": "Send OTP",
    "verifyOTP": "Verify OTP",
    "enterOTP": "Enter OTP",
    "otpSent": "OTP Sent",
    "otpSubtitle": "Enter the 6-digit code sent to",
    "resendOTP": "Resend OTP",
    "invalidOTP": "Please enter 6-digit OTP"
  },
  "cart": {
    "title": "Shopping Cart",
    "empty": "Your cart is empty",
    "emptyMessage": "Add some delicious rice products to your cart",
    "total": "Total",
    "subtotal": "Subtotal",
    "tax": "Tax",
    "delivery": "Delivery",
    "checkout": "Proceed to Checkout",
    "remove": "Remove",
    "quantity": "Quantity",
    "price": "Price",
    "continueShopping": "Continue Shopping",
    "discount": "Discount"
  },
  "profile": {
    "title": "Profile",
    "edit": "Edit Profile",
    "name": "Name",
    "email": "Email",
    "phone": "Phone",
    "address": "Address",
    "settings": "Settings",
    "language": "Language",
    "notifications": "Notifications",
    "help": "Help & Support",
    "privacy": "Privacy Policy",
    "terms": "Terms & Conditions",
    "logout": "Logout",
    "orderHistory": "Order History",
    "myOrders": "My Orders",
    "noOrders": "No orders yet",
    "orderDate": "Order Date",
    "orderStatus": "Status",
    "orderTotal": "Total"
  },
  "product": {
    "details": "Product Details",
    "description": "Description",
    "specifications": "Specifications",
    "reviews": "Reviews",
    "rating": "Rating",
    "reviewCount": "reviews",
    "addToCart": "Add to Cart",
    "buyNow": "Buy Now",
    "outOfStock": "Out of Stock",
    "inStock": "In Stock",
    "relatedProducts": "Related Products"
  },
  "categories": {
    "all": "All Categories",
    "rice": "Rice",
    "spices": "Spices",
    "oils": "Oils",
    "grains": "Grains"
  }
};

const kn = {
  "common": {
    "search": "ಉತ್ಪನ್ನಗಳನ್ನು ಹುಡುಕಿ...",
    "loading": "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    "error": "ದೋಷ",
    "success": "ಯಶಸ್ಸು",
    "ok": "ಸರಿ",
    "cancel": "ರದ್ದುಗೊಳಿಸಿ",
    "save": "ಉಳಿಸಿ",
    "edit": "ಸಂಪಾದಿಸಿ",
    "delete": "ಅಳಿಸಿ",
    "add": "ಸೇರಿಸಿ",
    "remove": "ತೆಗೆದುಹಾಕಿ",
    "yes": "ಹೌದು",
    "no": "ಇಲ್ಲ",
    "next": "ಮುಂದೆ",
    "previous": "ಹಿಂದೆ",
    "done": "ಮುಗಿದಿದೆ",
    "submit": "ಸಲ್ಲಿಸಿ",
    "continue": "ಮುಂದುವರಿಸಿ",
    "language": "ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ",
    "invalidEmail": "ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ.",
    "invalidPhone": "ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ 10 ಅಂಕಿಗಳ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ."
  },
  "navigation": {
    "products": "ಉತ್ಪನ್ನಗಳು",
    "explore": "ಅನ್ವೇಷಿಸಿ",
    "cart": "ಕಾರ್ಟ್",
    "profile": "ಪ್ರೊಫೈಲ್"
  },
  "home": {
    "welcome": "NVS ಅಕ್ಕಿ ಮಾಲ್‌ಗೆ ಸ್ವಾಗತ",
    "searchPlaceholder": "ಉತ್ಪನ್ನಗಳನ್ನು ಹುಡುಕಿ...",
    "all": "ಎಲ್ಲಾ",
    "categories": {
      "sonaMasooriRice": "ಸೋನಾ ಮಸೂರಿ ಅಕ್ಕಿ",
      "parboiledRice": "ಪಾರ್‌ಬಾಯಿಲ್ಡ್ ಅಕ್ಕಿ",
      "sonaMasooriSteamRice": "ಸೋನಾ ಮಸೂರಿ ಸ್ಟೀಮ್ ಅಕ್ಕಿ",
      "sonaMasooriRawRice": "ಸೋನಾ ಮಸೂರಿ ಕಚ್ಚಾ ಅಕ್ಕಿ",
      "rnrSteamRice": "RNR ಸ್ಟೀಮ್ ಅಕ್ಕಿ",
      "rnrRice": "RNR ಅಕ್ಕಿ",
      "rawRice": "ಕಚ್ಚಾ ಅಕ್ಕಿ",
      "giraRawRice": "ಗಿರಾ ಕಚ್ಚಾ ಅಕ್ಕಿ",
      "giraSteamRice": "ಗಿರಾ ಸ್ಟೀಮ್ ಅಕ್ಕಿ",
      "bowledRice": "ಬೌಲ್ಡ್ ಅಕ್ಕಿ",
      "brokenRice": "ಬ್ರೋಕನ್ ಅಕ್ಕಿ",
      "brokenSteamRice": "ಬ್ರೋಕನ್ ಸ್ಟೀಮ್ ಅಕ್ಕಿ",
      "brokenRawRice": "ಬ್ರೋಕನ್ ಕಚ್ಚಾ ಅಕ್ಕಿ",
      "basmatiRice": "ಬಾಸ್ಮತಿ ಅಕ್ಕಿ",
      "jasmineRice": "ಜಾಸ್ಮಿನ್ ಅಕ್ಕಿ",
      "italiaDosaRice": "ಇಟಾಲಿಯಾ ದೋಸೆ ಅಕ್ಕಿ",
      "hmtSteamRice": "HMT ಸ್ಟೀಮ್ ಅಕ್ಕಿ"
    },
    "noProductsFound": "ಯಾವುದೇ ಉತ್ಪನ್ನಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
    "tryDifferentSearch": "ವಿಭಿನ್ನ ಹುಡುಕಾಟ ಅಥವಾ ವರ್ಗವನ್ನು ಪ್ರಯತ್ನಿಸಿ",
    "addToCart": "ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ",
    "discountOff": "% ರಿಯಾಯಿತಿ"
  },
  "login": {
    "welcomeBack": "NVS ಅಕ್ಕಿ ಮಾಲ್‌ಗೆ ಮರಳಿ ಸ್ವಾಗತ",
    "email": "ಇಮೇಲ್",
    "password": "ಪಾಸ್‌ವರ್ಡ್",
    "login": "ಲಾಗಿನ್",
    "forgotPassword": "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?",
    "noAccount": "ಖಾತೆ ಇಲ್ಲವೇ?",
    "register": "ನೋಂದಣಿ",
    "fillAllFields": "ದಯವಿಟ್ಟು ಎಲ್ಲಾ ಕ್ಷೇತ್ರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ.",
    "featureComingSoon": "ಹೆಚ್ಚುವರಿ ವೈಶಿಷ್ಟ್ಯ ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ!",
    "phone": "ಫೋನ್",
    "enterPhone": "ಫೋನ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
    "sendOTP": "OTP ಕಳುಹಿಸಿ",
    "verifyOTP": "OTP ಪರಿಶೀಲಿಸಿ",
    "enterOTP": "OTP ನಮೂದಿಸಿ",
    "otpSent": "OTP ಕಳುಹಿಸಲಾಗಿದೆ",
    "otpSubtitle": "ಗೆ ಕಳುಹಿಸಲಾದ 6 ಅಂಕಿಗಳ ಕೋಡ್ ನಮೂದಿಸಿ",
    "resendOTP": "OTP ಮರು ಕಳುಹಿಸಿ",
    "invalidOTP": "ದಯವಿಟ್ಟು 6 ಅಂಕಿಗಳ OTP ನಮೂದಿಸಿ"
  },
  "cart": {
    "title": "ಶಾಪಿಂಗ್ ಕಾರ್ಟ್",
    "empty": "ನಿಮ್ಮ ಕಾರ್ಟ್ ಖಾಲಿ ಇದೆ",
    "emptyMessage": "ನಿಮ್ಮ ಕಾರ್ಟ್‌ಗೆ ಕೆಲವು ರುಚಿಕರ ಅಕ್ಕಿ ಉತ್ಪನ್ನಗಳನ್ನು ಸೇರಿಸಿ",
    "total": "ಒಟ್ಟು",
    "subtotal": "ಉಪ ಒಟ್ಟು",
    "tax": "ತೆರಿಗೆ",
    "delivery": "ವಿತರಣೆ",
    "checkout": "ಚೆಕ್‌ಔಟ್ ಮಾಡಿ",
    "remove": "ತೆಗೆದುಹಾಕಿ",
    "quantity": "ಪ್ರಮಾಣ",
    "price": "ಬೆಲೆ",
    "continueShopping": "ಶಾಪಿಂಗ್ ಮುಂದುವರಿಸಿ",
    "discount": "ರಿಯಾಯಿತಿ"
  },
  "profile": {
    "title": "ಪ್ರೊಫೈಲ್",
    "edit": "ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ",
    "name": "ಹೆಸರು",
    "email": "ಇಮೇಲ್",
    "phone": "ದೂರವಾಣಿ",
    "address": "ವಿಳಾಸ",
    "settings": "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    "language": "ಭಾಷೆ",
    "notifications": "ಅಧಿಸೂಚನೆಗಳು",
    "help": "ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ",
    "privacy": "ಗೌಪ್ಯತಾ ನೀತಿ",
    "terms": "ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು",
    "logout": "ಲಾಗ್‌ಔಟ್",
    "orderHistory": "ಆರ್ಡರ್ ಇತಿಹಾಸ",
    "myOrders": "ನನ್ನ ಆರ್ಡರ್‌ಗಳು",
    "noOrders": "ಇನ್ನೂ ಯಾವುದೇ ಆರ್ಡರ್‌ಗಳಿಲ್ಲ",
    "orderDate": "ಆರ್ಡರ್ ದಿನಾಂಕ",
    "orderStatus": "ಸ್ಥಿತಿ",
    "orderTotal": "ಒಟ್ಟು"
  },
  "product": {
    "details": "ಉತ್ಪನ್ನದ ವಿವರಗಳು",
    "description": "ವಿವರಣೆ",
    "specifications": "ವಿಶೇಷಣಗಳು",
    "reviews": "ಸಮೀಕ್ಷೆಗಳು",
    "rating": "ರೇಟಿಂಗ್",
    "reviewCount": "ಸಮೀಕ್ಷೆಗಳು",
    "addToCart": "ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ",
    "buyNow": "ಈಗ ಖರೀದಿಸಿ",
    "outOfStock": "ಸ್ಟಾಕ್ ಇಲ್ಲ",
    "inStock": "ಸ್ಟಾಕ್ ಇದೆ",
    "relatedProducts": "ಸಂಬಂಧಿತ ಉತ್ಪನ್ನಗಳು"
  },
  "categories": {
    "all": "ಎಲ್ಲಾ ವರ್ಗಗಳು",
    "rice": "ಅಕ್ಕಿ",
    "spices": "ಮಸಾಲೆಗಳು",
    "oils": "ಎಣ್ಣೆಗಳು",
    "grains": "ಧಾನ್ಯಗಳು"
  }
};

const strings = new LocalizedStrings({
  en: en,
  kn: kn,
});

export default strings;